default_environment: test
jira: ~
environments:
  test:
    deployments: ~/deployments
    database:
      mysql:
        host: localhost
        port: 3306
        user: root
        pass: ~
        name: test
        charset: utf8