#!/usr/bin/env php
<?php

use Deployee\Core\Console\Application;
use Deployee\Core\Console\Commands\CreateCommand;
use Deployee\Core\Console\Commands\DeployCommand;
use Deployee\Core\Console\Commands\DescribeCommand;
use Deployee\Core\Console\Commands\InitCommand;

$container = require_once __DIR__ . '/../bootstrap.php';

/* @var Application $app */
$app = $container['console'];

$app->add(new InitCommand());
$app->add(new DeployCommand());
$app->add(new DescribeCommand());
$app->add(new CreateCommand());

$app->run();